name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
    - name: Install pdflatex
      run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra
    - name: Build pdf
      run: make kactl
    - name: Run compiles
      run: make test-compiles
    - name: Run stress tests
      run: make test
    - name: Trust Directory
      run: |
        git config --global --add safe.directory ${GITHUB_WORKSPACE}
      # https://github.com/actions/checkout/issues/760
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: auto build - ${{ github.sha }}
        branch: build
        create_branch: true
        push_options: -f
